name: Docker Image CI

on:
  pull_request:
    branches: [ "build" ]
jobs:

  build:
  
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.TAS_BE_TOKEN}}
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: |
            docker build ./ -f ./TAS.API/Dockerfile --tag ghcr.io/thinhnche153157/tas_project_be:latest --tag ghcr.io/thinhnche153157/tas_project_be:${{ steps.vars.outputs.sha_short }}
            docker push ghcr.io/thinhnche153157/tas_project_be:latest  
            docker push ghcr.io/thinhnche153157/tas_project_be:${{ steps.vars.outputs.sha_short }}
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
          username: root
          host: 103.179.173.136
          key: ${{secrets.SSH_PASSWORD}}
          script: |
            docker stop tas_project_be || true  
            docker rm tas_project_be || true  
            docker rmi ghcr.io/thinhnche153157/tas_project_be:latest || true 
            docker run -d --name tas_project_be --restart on-failure:5 -p 5000:80 -e ASPNETCORE_ENVIRONMENT=Development -e ASPNETCORE_URLS=http://+:80 -e ConnectionStrings__Default="server=TAS;uid=sa;pwd=@TAS12345;database=TAS;Encrypt=False" ghcr.io/thinhnche153157/tas_project_be:latest
